-- sowwwl API schema (MySQL)
CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(190) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  status ENUM('active','pending','banned') DEFAULT 'active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS profiles (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  handle VARCHAR(64) UNIQUE NOT NULL,
  display_name VARCHAR(128) NULL,
  state_o ENUM('0','O') DEFAULT '0',
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS identities (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  comm_address VARCHAR(190) UNIQUE NOT NULL,
  type ENUM('internal','email') DEFAULT 'internal',
  verified BOOLEAN DEFAULT FALSE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS botes (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  title VARCHAR(128) NULL,
  content MEDIUMTEXT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_user_bote (user_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- UX state (server-driven flip token for multi-device sync)
CREATE TABLE IF NOT EXISTS ux_state (
  user_id INT UNSIGNED PRIMARY KEY,
  flip_seq INT UNSIGNED NOT NULL DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Admin magic-link auth (email, one-time, expiring)
CREATE TABLE IF NOT EXISTS admin_magic_links (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  email_hash CHAR(64) NOT NULL,
  token_hash CHAR(64) NOT NULL,
  issued_host VARCHAR(190) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  expires_at DATETIME NOT NULL,
  used_at DATETIME NULL,
  send_ok BOOLEAN NOT NULL DEFAULT FALSE,
  send_error VARCHAR(64) NULL,
  used_ip VARCHAR(64) NULL,
  used_ua VARCHAR(190) NULL,
  UNIQUE KEY uniq_token_hash (token_hash),
  INDEX idx_user_created (user_id, created_at),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Links between people (minimal social graph)
CREATE TABLE IF NOT EXISTS connections (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_a INT UNSIGNED NOT NULL,
  user_b INT UNSIGNED NOT NULL,
  requested_by INT UNSIGNED NOT NULL,
  status ENUM('pending','accepted','blocked') NOT NULL DEFAULT 'pending',
  blocked_by INT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_pair (user_a, user_b),
  INDEX idx_user_a (user_a),
  INDEX idx_user_b (user_b),
  INDEX idx_status (status),
  FOREIGN KEY (user_a) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (user_b) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (requested_by) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (blocked_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Doors (public, identity-less entry points) + coarse presence
CREATE TABLE IF NOT EXISTS doors (
  user_id INT UNSIGNED PRIMARY KEY,
  door_id CHAR(32) NOT NULL UNIQUE,
  tz_offset_min SMALLINT NULL,
  lat_q SMALLINT NULL,
  lon_q SMALLINT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Cour (public personal space; no private interaction here)
CREATE TABLE IF NOT EXISTS cour (
  user_id INT UNSIGNED PRIMARY KEY,
  content MEDIUMTEXT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Qu3st (global quest text; edited via 4nOd3)
CREATE TABLE IF NOT EXISTS qu3st (
  id TINYINT UNSIGNED PRIMARY KEY,
  content MEDIUMTEXT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Ensure row 1 exists (do not overwrite existing content)
INSERT IGNORE INTO qu3st (id, content) VALUES (1, '');

-- Land (personal space metadata)
CREATE TABLE IF NOT EXISTS land (
  user_id INT UNSIGNED PRIMARY KEY,
  land_type ENUM('A','B','C') NULL,
  lambda_val DECIMAL(5,3) NULL,
  beaute_text MEDIUMTEXT NULL,
  beaute_updated_at TIMESTAMP NULL,
  glyph VARCHAR(8) NULL,
  o_seed_line VARCHAR(512) NULL,
  seal VARCHAR(64) NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Land theme (derived from glyph; deterministic; used for colorimetry)
CREATE TABLE IF NOT EXISTS land_theme (
  user_id INT UNSIGNED PRIMARY KEY,
  glyph VARCHAR(8) NOT NULL,
  hue SMALLINT UNSIGNED NOT NULL,
  sat TINYINT UNSIGNED NOT NULL,
  lum TINYINT UNSIGNED NOT NULL,
  contrast DECIMAL(6,3) NOT NULL,
  invert_on_click BOOLEAN NOT NULL DEFAULT TRUE,
  theme_updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Quest DELTA (4n0d3)
CREATE TABLE IF NOT EXISTS quest_delta (
  user_id INT UNSIGNED PRIMARY KEY,
  state ENUM('IDLE','RUNNING','ENDED') NOT NULL DEFAULT 'IDLE',
  step TINYINT UNSIGNED NOT NULL DEFAULT 0,
  beauty_text VARCHAR(512) NULL,
  passage_choice VARCHAR(32) NULL,
  land_glyph VARCHAR(8) NULL,
  o_seed_line VARCHAR(512) NULL,
  seal VARCHAR(64) NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Quest DELTA extra metadata (kept separate for schema idempotency)
CREATE TABLE IF NOT EXISTS quest_delta_meta (
  user_id INT UNSIGNED PRIMARY KEY,
  coherence_score DECIMAL(6,3) NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- B0te unlock window (granted by quests; used to gate creation)
CREATE TABLE IF NOT EXISTS bote_unlock (
  user_id INT UNSIGNED PRIMARY KEY,
  unlock_until DATETIME NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- B0te (v2): draft + validated visibility window + archival
CREATE TABLE IF NOT EXISTS bote_entries (
  user_id INT UNSIGNED PRIMARY KEY,
  status ENUM('DRAFT','VISIBLE','ARCHIVED') NOT NULL DEFAULT 'DRAFT',
  languages VARCHAR(128) NULL,
  content MEDIUMTEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  validated_at TIMESTAMP NULL,
  expires_at DATETIME NULL,
  glyph VARCHAR(8) NULL,
  archetype VARCHAR(32) NULL,
  seed_path VARCHAR(255) NULL,
  first_line VARCHAR(512) NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- b0n uZe (behavioral charter; alphabetic equilibrium state)
CREATE TABLE IF NOT EXISTS bonuze_state (
  user_id INT UNSIGNED PRIMARY KEY,
  version INT NOT NULL DEFAULT 1,
  consented_at DATETIME NULL,
  ok BOOLEAN NOT NULL DEFAULT FALSE,
  locked BOOLEAN NOT NULL DEFAULT FALSE,
  state_index TINYINT UNSIGNED NOT NULL DEFAULT 14,
  state_letter CHAR(1) NOT NULL DEFAULT 'O',
  flags_json TEXT NULL,
  last_eval_at DATETIME NULL,
  last_event_at DATETIME NULL,
  last_change_at DATETIME NULL,
  osc_dir TINYINT NOT NULL DEFAULT 1,
  actions_5m DECIMAL(7,2) NOT NULL DEFAULT 0,
  actions_1h DECIMAL(7,2) NOT NULL DEFAULT 0,
  edits_1m DECIMAL(7,2) NOT NULL DEFAULT 0,
  repeats_1h DECIMAL(7,2) NOT NULL DEFAULT 0,
  noise_1h DECIMAL(7,2) NOT NULL DEFAULT 0,
  threats_30d INT NOT NULL DEFAULT 0,
  threat_last_at DATETIME NULL,
  last_sig VARCHAR(64) NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- soul.cloud (token + archive uploads, V0)
CREATE TABLE IF NOT EXISTS soul_cloud (
  user_id INT UNSIGNED PRIMARY KEY,
  token_sha256 CHAR(64) NOT NULL,
  token_hint VARCHAR(16) NOT NULL,
  config_json MEDIUMTEXT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS soul_uploads (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  archive_name VARCHAR(255) NOT NULL,
  archive_bytes BIGINT UNSIGNED NOT NULL,
  archive_sha256 CHAR(64) NOT NULL,
  archive_path VARCHAR(255) NOT NULL,
  manifest_json MEDIUMTEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_user_created (user_id, created_at),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
